### ISSUE TITLE
显示出现乱码

### ISSUE THREAD

**Issue by senseab** [WeCase/WeCase#104]
![5](https://f.cloud.github.com/assets/2174238/1938397/0b521978-7f48-11e3-83a3-7eb3cc044421.png)

**Comment by senseab** [comment]
```
微博开放平台开放接口，中文字符处理出现短暂性故障，刀子已经架在工程师脖子上了，有新的进展会及时通知大家，请不要慌张哦~ [泪] [泪] [泪]
```

果然是渣浪

**Comment by cthbleachbit** [comment]
我这里很正常啊

On Jan 17, 2014, at 03:57 PM, TonyChyi notifications@github.com wrote:

微博开放平台开放接口，中文字符处理出现短暂性故障，刀子已经架在工程师脖子上了，有新的进展会及时通知大家，请不要慌张哦~ [泪] [泪] [泪] 
果然是渣浪
