### ISSUE TITLE
sh - bash vs. dash / AttributeError: 'TweetUserModel' object has no attribute 'wordWarKeywords'

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#105]
<p>不知道是不是我的 Debian 缺少了什么包导致的，不过我在新立德找了 python3-pyqt4 ，我已经全部安装了～</p>

<pre><code>
Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/WeCase/Tweet.py", line 414, in _rowsInserted
    filteredTweets = self.filter(tweets)
  File "/usr/local/lib/python3/dist-packages/WeCase/Tweet.py", line 400, in filter
    new_items = self.wordWarFilter(new_items)
  File "/usr/local/lib/python3/dist-packages/WeCase/Tweet.py", line 368, in wordWarFilter
    if item.withKeywords(self.wordWarKeywords):
  File "/usr/local/lib/python3/dist-packages/WeCase/Tweet.py", line 436, in __getattr__
    return eval("self._model.%s" % attr)
  File "<string>", line 1, in <module>
AttributeError: 'TweetUserModel' object has no attribute 'wordWarKeywords'
</code></pre>

**Comment by Garfield550** [comment]
<p>还有我不知道这一串 NotFound 代指什么</p>

<pre><code>
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 6: /usr/local/bin/wecase: [[: not found
/usr/local/bin/wecase: 12: [: unexpected operator
</code></pre>

**Comment by biergaizi** [comment]
大概是生成的 Bash 脚本也有问题……你能把

```
/usr/local/bin/wecase
```

的内容也传上来吗？

**Comment by Garfield550** [comment]
我大概明天可以传上来

**Comment by Garfield550** [comment]
抱歉发晚了，我以为你要先忙一阵子才能有时间。

<pre><code>
#!/bin/sh
for py in `whereis -b python | sed 's/^python: //'`
do
    version=`$py -V 2>&1`
    if [[ "$version" == *"Python 3"* ]]; then
        python3=$py
        break
    fi
done
if [ "$python3" == "" ]; then
    exit 1;
fi
exec $python3 /usr/local/libexec/wecase.py
</code></pre>

**Comment by Garfield550** [comment]
###这个邮箱还在用吗？###

> Gravatar Email (Private)
> 
> avatar@wecaseproject.tk

**Comment by biergaizi** [comment]
@Garfield550 专门用来提供头像的。另外不要在 Issue 发表无关话题难以检索，下次直接删除。

**Comment by biergaizi** [comment]
看看 ce4fa65 能不能解决 `/usr/local/bin/wecase` 的出错问题。当然，要重新编译。

**Comment by biergaizi** [comment]
问题应该都修正了，请测试。有问题请 Reopen。
