### ISSUE TITLE
获取通知时仍然会锁死界面

### ISSUE THREAD

**Issue by biergaizi** [WeCase/WeCase#11]
获取通知时，整个界面会失去响应。
务必请 @tonychee7000 抽时间复查一下线程机制。

**Comment by cthbleachbit** [comment]
我的Ubuntu 好像没有出现这种情况

**Comment by Garfield550** [comment]
貌似没有这种情况！

**Comment by biergaizi** [comment]
获取通知的间隔是 30 秒一次，在此期间打开“发微博”对话框，输入文字，有无假死？

**Comment by Garfield550** [comment]
没发现！无最新消息~

**Comment by senseab** [comment]
问题找到了，在操作界面元素时，也是死锁的
现在还搞不定这个……tasukete

**Comment by biergaizi** [comment]
@tonychee7000 到时候我来吧，Python 的伪多线程不行，还可以多进程嘛。

**Comment by biergaizi** [comment]
@tonychee7000 Python 3 中的 `_thread` 模块快被废弃了，我准备用 `threading` 或者多进程重写。

**Comment by senseab** [comment]
收到！

**Comment by biergaizi** [comment]
@tonychee7000 已在 4bfd15c1a6cff62d305668f1d87bd94efe24777e 中替换掉 `_thread`

**Comment by biergaizi** [comment]
已在 8772bd06649dd89e8adf03aa50f1ebf791249fee 中修正该问题，并在随后实现界面完全多线程。
