### ISSUE TITLE
MATE 下的布局问题

### ISSUE THREAD

**Issue by biergaizi** [WeCase/WeCase#112]
依然是”关于“窗口的布局。这个窗口的长宽都是按照当时设计的固定值，导致了内容被截断。

![About Window](https://f.cloud.github.com/assets/1310693/2256713/6f4bc2c6-9e0b-11e3-8bf1-c338d51b6338.png)

**Comment by Garfield550** [comment]
果然偏了。

于 (ノﾟДﾟ)ノ [ 2 25 ] 18:56, Tom Li 写道:

**Comment by biergaizi** [comment]
@Garfield550 这不是重点..

**Comment by Garfield550** [comment]
那是什么

于 (ノﾟДﾟ)ノ [ 2 26 ] 15:36, Tom Li 写道:

**Comment by biergaizi** [comment]
@Garfield550 最后一行文字被截断了.

**Comment by Garfield550** [comment]
我去，是这个

于 (ノﾟДﾟ)ノ [ 2 27 ] 8:50, Tom Li 写道:
