### ISSUE TITLE
openSUSE编译错误

### ISSUE THREAD

**Issue by SunRain** [WeCase/WeCase#117]
openSUSE13.1 64位系统,尝试编译安装,错误如下
/path/to/WeCase> ./configure
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for a Python interpreter with version >= 3.2... python3
checking for python3... /usr/bin/python3
checking for python3 version... 3.3
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3.3/site-packages
checking for python3 extension module directory... ${exec_prefix}/lib64/python3.3/site-packages
checking python module: PyQt4... yes
checking python module: weibo3... yes
checking python module: notify2... yes
checking for pyuic4... yes
checking for pyrcc4... yes
checking for lrelease... lrelease
checking for Git commit SHA1... 9ef2f52-dirty
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating locale/Makefile
config.status: creating res/Makefile

/path/to/WeCase> make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /path/to/WeCase/WeCase/missing --run aclocal-1.11 
/path/to/WeCase/missing:行81: aclocal-1.11: 未找到命令
WARNING: 'aclocal-1.11' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         http://www.gnu.org/software/automake
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         http://www.gnu.org/software/autoconf
         http://www.gnu.org/software/m4/
         http://www.perl.org/
make: **\* [aclocal.m4] 错误 127

whereis aclocal提示
aclocal: /usr/bin/aclocal /usr/share/aclocal /usr/share/man/man1/aclocal.1.gz

**Comment by biergaizi** [comment]
这种问题，是因为系统的 automake 版本太新或太旧，不能保证每个系统的 automake 版本都一样。这是 Packagers 的常识。在源码树根目录进行 autoreconf 即可解决问题。

Gentoo 为了安全，会对每个源码包提前进行这样处理。

我会补充相关文档的。

**Comment by biergaizi** [comment]
另外，你也没有按照文档规范操作。

```
# Build and Install
mkdir build
cd build
../configure
make
sudo make install
```

向 gcc 这样的项目，都是不允许在源码树下直接编译的。
