### ISSUE TITLE
aclocal-1.11: 未找到命令 但我已经安装了

### ISSUE THREAD

**Issue by craware** [WeCase/WeCase#118]
<code>
jiangping328353@deepin:~/WeCase/build$ make
CDPATH="${ZSH_VERSION+.}:" && cd .. && /bin/bash /home/jiangping328353/WeCase/missing --run aclocal-1.11 
/home/jiangping328353/WeCase/missing: 行 81: aclocal-1.11: 未找到命令
WARNING: 'aclocal-1.11' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         http://www.gnu.org/software/automake
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         http://www.gnu.org/software/autoconf
         http://www.gnu.org/software/m4/
         http://www.perl.org/
make: **\* [../aclocal.m4] 错误 127
</code>
我已经安装了最新版

<code>
jiangping328353@deepin:~/WeCase/build$ aclocal --version
aclocal (GNU automake) 1.13.2
Copyright (C) 2013 Free Software Foundation, Inc.
</code>

**Comment by Garfield550** [comment]
安装 Automake 1.11
----- 原始邮件 -----
发件人：craware notifications@github.com
收件人：WeCase/WeCase WeCase@noreply.github.com
主题：[WeCase]_aclocal-1.11:_未找到命令_但我已经安装了_(#118)
日期：2014年03月25日 13点25分

**Comment by biergaizi** [comment]
Duplicate of #117.

**Comment by biergaizi** [comment]
另外，你不认识数字吗……
