### ISSUE TITLE
statuses/user_timeline.json 接口被限制

### ISSUE THREAD

**Issue by biergaizi** [WeCase/WeCase#119]
## 错误报告（感谢 [@Di-Lover](http://weibo.com/didilover) 的确认）

```
苍天啊，大地啊！这个不明错误怎么就发生了呢，
Please report it to <http://bugs.wecase.org/>
------------[ cut here ]------------
Version: WeCase 0.06-beta5-2456d12
Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/WeCase/WeHack.py", line 30, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3/dist-packages/WeCase/Tweet.py", line 99, in _common_get
    timeline = timeline_func()
  File "/usr/local/lib/python3/dist-packages/WeCase/Tweet.py", line 157, in timeline_get
    timeline = self.timeline.get(page=page, uid=self._uid).statuses
  File "/usr/local/lib/python3/dist-packages/WeCase/weibos/client.py", line 52, in __call__
    return super(_UBExecutable, self).__call__(**kw)
  File "/usr/local/lib/python3.2/dist-packages/weibo3.py", line 291, in __call__
    return _http_call('%s%s.json' % (self._client.api_url, self._path), method, self._client.access_token, **kw)
  File "/usr/local/lib/python3.2/dist-packages/weibo3.py", line 161, in _http_call
    raise APIError(r.error_code, r.get('error', ''), r.get('request', ''))
weibo3.APIError: APIError: 21335: request uid's value must be the current user, request: /2/statuses/user_timeline.json
---[ end trace 0xc7cfbfc ]---
```
## 说明

去年末的时候，新浪就曾有传言要限制此接口，引起开发者们的强烈反弹。后来，新浪并没有限制此接口，并在说明中提到

> 接口升级后：uid 与 screen_name 只能为当前授权用户，第三方微博类客户端不受影响

然而，今年初开始，这个接口便出现此问题，从

> request uid's value must be the current user

上上述说明也依然在文档中，没有任何改变，新浪似乎出尔反尔，限制此接口的使用，严重影响第三方客户端。

我在本地也可 100% 复现此问题，但是 @cthbleachbit 称他那里没有问题，不知何故。

**Comment by biergaizi** [comment]
@cthbleachbit 请确认。

**Comment by biergaizi** [comment]
@cthbleachbit 已在微博上确认。

**Comment by biergaizi** [comment]
暂时显示一个给用户的提示。

**Comment by Garfield550** [comment]
...

**Comment by biergaizi** [comment]
statuses/user_timeline.json 确实被封掉了。把 WeCase 的 Key 和 Secret 换成四次元就都正常了，看来是因为使用人数多，新浪没对四次元下手……使用人数少的都挂了。

**Comment by biergaizi** [comment]
发现了服务器的一个漏洞，有机会从这个接口上或取数据。

<del>作战</del>代号：Hacking to the server！行动顺利完成：

https://github.com/WeCase/sinaweibopy/commit/09c3f1d3b6cc9dcc17ab47a9df14025bb7d594d5
https://github.com/WeCase/WeCase/commit/cd987fe45fe1c84116a45808ff494ad13ee541b0
https://github.com/WeCase/WeCase/commit/61f2b916afd04f1e88413e6439fe4c187f727fff
https://github.com/WeCase/WeCase/commit/feacb510255246341733511762956802a0c379c6

之后，现在，WeCase 暂时又可以获取他人的微博了，虽然这代码修改的很恶心。

**Comment by biergaizi** [comment]
不知道这个方法能用多久。

El Psy Congroo.

**Comment by neruthes** [comment]
だから今。。。

**Comment by neruthes** [comment]
だから今。。。

**Comment by Garfield550** [comment]
@JoyNeop 照顾一下中国人

**Comment by hiapk** [comment]
来看代号
