### ISSUE TITLE
转发时，原微博成了输入框内的文字，导致字数过多

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#12]
![2013-03-10 16:18:05 ](https://f.cloud.github.com/assets/3471836/240889/6f1ce63c-895c-11e2-885b-2bd2ebbcdc11.png)

**Comment by biergaizi** [comment]
还是有点失误，等会儿修复。

**Comment by Garfield550** [comment]
好

**Comment by biergaizi** [comment]
@Garfield550 无法重现此问题～～

**Comment by biergaizi** [comment]
@Garfield550 请给出能引发此问题的单条微博链接，以便我进行调试（点击微博时间即可获得链接）

**Comment by Garfield550** [comment]
……转发长些的微博

**Comment by Garfield550** [comment]
http://e.weibo.com/1772191555/zmNxzEOTX 试试这个

**Comment by Garfield550** [comment]
![2013-03-10 16:41:32 ](https://f.cloud.github.com/assets/3471836/240896/5577e4f0-895e-11e2-8990-e4fd7a14408e.png)

Bug重现！

**Comment by biergaizi** [comment]
在 94a51952eff11178e77b9fab1fa070180653e661 修复了，你没更新吧……

**Comment by Garfield550** [comment]
![Uploading 2013-03-10 16:56:26的屏幕截图.png . . .]()
