### ISSUE TITLE
启动脚本应优先选择系统“偏爱”的 Python 版本。

### ISSUE THREAD

**Issue by biergaizi** [WeCase/WeCase#122]
## 描述

系统上同时安装了 Python 2.7, Python 3.2, Python 3.3, Python 3.4，而 Python 3.3 是系统在使用的 Python，模块齐全，而剩下的 Python 则是实验用的。这种情况下，`wecase` 这个脚本会随意选择 Python，从而找不到模块。

应该优先运行 `python3`，然后再大规模搜索。

**Comment by xdqi** [comment]
判断各版本 site-package 中库（文件夹数）多少如何

**Comment by Garfield550** [comment]
...文件夹数量
----- 原始邮件 -----
发件人：ehs2013 notifications@github.com
收件人：WeCase/WeCase WeCase@noreply.github.com
主题：Re:_[WeCase]_启动脚本应优先选择系统“偏爱”的_Python_版本。_(#122)
日期：2014年05月02日 12点43分

**Comment by biergaizi** [comment]
正常情况下，`python3` 所指向的 Python 就应该是偏爱的 Python 版本。
