### ISSUE TITLE
Notification Daemon is not running?

### ISSUE THREAD

**Issue by MingcongBai** [WeCase/WeCase#132]
"通知守护进程 (Notification Daemon) 不存在。通知将禁用。" While notify2 (Python2 + Python3) is installed.

Output of dpkg -L notify2:

/.
/usr
/usr/lib
/usr/lib/python3.4
/usr/lib/python3.4/site-packages
/usr/lib/python3.4/site-packages/notify2.py
/usr/lib/python3.4/site-packages/notify2-0.3-py3.4.egg-info
/usr/lib/python3.4/site-packages/**pycache**
/usr/lib/python3.4/site-packages/**pycache**/notify2.cpython-34.pyo
/usr/lib/python3.4/site-packages/**pycache**/notify2.cpython-34.pyc
/usr/lib/python2.7
/usr/lib/python2.7/site-packages
/usr/lib/python2.7/site-packages/notify2.py
/usr/lib/python2.7/site-packages/notify2.pyo
/usr/lib/python2.7/site-packages/notify2-0.3-py2.7.egg-info
/usr/lib/python2.7/site-packages/notify2.pyc

DBus is installed of course...

**Comment by Garfield550** [comment]
检查一下环境变量
然后在终端启动 python 3.4 输入 import notify2 试试

**Comment by MingcongBai** [comment]
No error was returned anyway.

**Comment by Garfield550** [comment]
那需要等盖子了

**Comment by MingcongBai** [comment]
I believe our D-Bus server is running properly... well let's wait for the
expert.

**Comment by biergaizi** [comment]
possible duplicate for Issue #82.

**Comment by biergaizi** [comment]
@TheNextProject Please read #82 first.

**Comment by MingcongBai** [comment]
I didn't get the error output, I am reading the wiki you provided now.

**Comment by MingcongBai** [comment]
Got it, it's xfce4-notifyd. Please close this then. But I guess somehow you
need a prompt for installation at the README file.
