### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by PeterCxy** [WeCase/WeCase#133]
Oops, there is an unexpected error,
Please report it to http://bugs.wecase.org/
------------[ cut here ]------------

Version: WeCase 0.06-beta8-unknown

Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/rpweibo.py", line 34, in header_callback
    self.hdr += x.decode("ascii")
AttributeError: 'str' object has no attribute 'decode'
---[ end trace 0x7fa867254bf0 ]---

python版本3.3，直接从gentoo-zh里面emerge的

**Comment by PeterCxy** [comment]
登录的时候出现的

**Comment by biergaizi** [comment]
Fixed in https://github.com/WeCase/rpweibo/commit/56d26284b29e6be5069645cce675fd2c92389ab1
