### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type SingleTweetWidget has been deleted

### ISSUE THREAD

**Issue by ghost** [WeCase/WeCase#134]
Version: WeCase 0.06-beta7-unknown

Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/WeCase/TweetListWidget.py", line 617, in drawAnimate
    sender = self.sender()
RuntimeError: wrapped C/C++ object of type SingleTweetWidget has been deleted
---[ end trace 0x7fb3ad0cc410 ]---

**Comment by biergaizi** [comment]
这也能被垃圾回收，我真是服了……

**Comment by biergaizi** [comment]
Fixed in https://github.com/WeCase/WeCase/commit/f6b4097679c87f09fa7ff169cfb867a88ebeea27.
