### ISSUE TITLE
PyQt 会调用不存在的 slot，从而引发一系列问题

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#135]
```
------------[ cut here ]------------

Version: WeCase 0.06-beta7-unknown

Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/WeCase/WeHack.py", line 30, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3/dist-packages/WeCase/Tweet.py", line 111, in _common_get
    self.nothingLoaded.emit()
TypeError: pyqtSignal must be bound to a QObject, not 'TweetUserModel'
---[ end trace 0xaf526ecc ]---
```

在关闭标签的时候发生错误，但是没能重现

**Comment by biergaizi** [comment]
又是垃圾回收。

**Comment by biergaizi** [comment]
很简单。一切又是由于现有的异步模型的缺陷，可以这么理解：

| 窗体线程 | API 线程 |
| --- | --- |
| 需要获取信息 | - |
|  | 启动 |
| - | 加载中 |
| (用户关闭窗体) | ... |
| None | 加载完成，回调窗体线程 |
| - | **错误：对象不存在** |

**Comment by biergaizi** [comment]
新创建了一个 common-async 标签用来标记所有此类问题。你可以看到你非常得多，在不同的点出现的，但本质一样。我目前只能 try/except。问题等重写异步模型_（怎么出来补魔了……）_后才能彻底解决。

**Comment by cthbleachbit** [comment]
是在加载完之前就直接关掉tab的后果，，怪网速咯。。

**Comment by biergaizi** [comment]
我终于知道所有这一系列 Bug 的真相了，

> In previous versions, when a signal was emitted to a Python slot that was not decorated with pyqtSlot(), it would not check that the underlying C++ receiver instance still existed. 

而在 PyQt v4.11 中

> By default a Python slot is only invoked if the underlying C++ instance still exists.

这就解释了
- 不存在的对象会被回调；以及
- 并不是所有人的机器上都会出错

两大疑问。

**Comment by biergaizi** [comment]
通过标记一系列 slot 为 `@QtCore.pyqtSlot()`，这个问题应该已经初步得到解决。
