### ISSUE TITLE
Ubuntu PPA 貌似有问题

### ISSUE THREAD

**Issue by kerraway** [WeCase/WeCase#136]
贴上执行 sudo add-apt-repository ppa:wecase/ppa 命令后的提示：

 WeCase Project is a open source project, to develop a Full-Featured Sina Weibo Client. It is not just a client project, it is also maintain a Python 3 Version of Weibo SDK.
 更多信息： https://launchpad.net/~wecase/+archive/ubuntu/ppa
按回车继续或者 Ctrl+c 取消添加

gpg: 钥匙环‘/tmp/tmp0by40hje/secring.gpg’已建立
gpg: 钥匙环‘/tmp/tmp0by40hje/pubring.gpg’已建立
gpg: 下载密钥‘63D92C24’，从 hkp 服务器 keyserver.ubuntu.com
?: [fd 4]: read error: Connection reset by peer
gpgkeys: HTTP fetch error 7: couldn't connect: eof
gpg: 找不到有效的 OpenPGP 数据。
gpg: 合计被处理的数量：0

**Comment by kerraway** [comment]
sudo apt-get update 后，

下载 836 B，耗时 5分 57秒 (2 B/s)
正在读取软件包列表... 完成
W: GPG 错误：http://ppa.launchpad.net trusty Release: 由于没有公钥，无法验证下列签名： NO_PUBKEY 194FE5DA63D92C24

**Comment by kerraway** [comment]
sudo apt-get install wecase 后，

正在读取软件包列表... 完成
正在分析软件包的依赖关系树  
正在读取状态信息... 完成  
将会安装下列额外的软件包：
  python3-notify2 python3-pyqt4 python3-rpweibo
建议安装的软件包：
  python3-pyqt4-dbg
下列【新】软件包将被安装：
  python3-notify2 python3-pyqt4 python3-rpweibo wecase
升级了 0 个软件包，新安装了 4 个软件包，要卸载 0 个软件包，有 3 个软件包未被升级。
需要下载 6,484 kB 的软件包。
解压缩后会消耗掉 20.4 MB 的额外空间。
您希望继续执行吗？ [Y/n] y
【警告】：下列软件包不能通过验证！
  python3-rpweibo wecase
不经验证就安装这些软件包吗？ [y/N]

**Comment by biergaizi** [comment]
```
gpg: 下载密钥‘63D92C24’，从 hkp 服务器 keyserver.ubuntu.com
?: [fd 4]: read error: Connection reset by peer
gpgkeys: HTTP fetch error 7: couldn't connect: eof
```

这么明显的问题你都看不出来？一切都是因为第一步下载密钥的时候失败，导致后面就都是未验证了。而失败的原因是莫名被墙了。

**Comment by kerraway** [comment]
抱歉，估计是之前的网络问题，我现在试了，密钥下载成功，没挂VPN

**Comment by biergaizi** [comment]
嗯，RST 不是墙，纯属网络不稳定。唉，网络真的不是一个可靠的东西啊。
