### ISSUE TITLE
是否使用新图标？

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#138]
![wecase-long-shadow](https://cloud.githubusercontent.com/assets/3471836/3870828/7587ce1a-20e1-11e4-92d7-6a3ef1e12fe2.png)

**Comment by biergaizi** [comment]
IRC 开会表决。

**Comment by biergaizi** [comment]
网站可以随便，但是主程序必须走议会程序。

**Comment by Garfield550** [comment]
明晚？

**Comment by biergaizi** [comment]
最近在忙 DRM/KMS 驱动，提前放个通知，最好找个全体成员都能来的时间。就一个小时也不讨论太多具体东西。

**Comment by Garfield550** [comment]
老样子晚上8点么？

**Comment by biergaizi** [comment]
> 提前放个通知

我没说清楚。我的意思是放个开会的通知，然后商定一下全体成员都能来的日期和时间。不是明天。

**Comment by biergaizi** [comment]
范围在一周之内吧。

**Comment by Garfield550** [comment]
@biergaizi 我已经发了

**Comment by biergaizi** [comment]
@Garfield550 那就撤销吧。反正明天我都没时间去。

**Comment by Garfield550** [comment]
@biergaizi 看来还是即时社交通信讨论问题比较好

**Comment by cthbleachbit** [comment]
另外关于违和的托盘图标，有什么方案么

**Comment by Garfield550** [comment]
@cthbleachbit 我想，应该换成 SVG 吧。
@biergaizi 会议讨论的事情你来安排吧，我不清楚大家具体有空的时间。

**Comment by Garfield550** [comment]
强制决定采用，没有为什么

**Comment by biergaizi** [comment]
如果 API 也能像这样强制使用就好了……

**Comment by Garfield550** [comment]
可能也是最近整顿吧，新浪几乎把没什么人用的第三方客户端的 API 都限制了

**Comment by Garfield550** [comment]
图标是这个
![](https://raw.githubusercontent.com/WeCase/WeCase-icon/master/View/long-shadow-square.png)

在暖色屏幕上，红色真扎眼……

**Comment by cthbleachbit** [comment]
加个阴影瞬间Materialize了。。
On Apr 12, 2015 1:39 PM, Stark Li notifications@github.com wrote:图标是这个
