### ISSUE TITLE
建议以及问题

### ISSUE THREAD

**Issue by love4taylor** [WeCase/WeCase#140]
建议设置里可选最小化方式。然后就是以下的界面UI。。另，一旦输入类似😘额符号，就无法发送微博。
![2014-09-23 18 07 40](https://cloud.githubusercontent.com/assets/6081912/4371615/f7b8b278-4319-11e4-988e-515aac5c4ef8.png)
![2014-09-23 18 02 55](https://cloud.githubusercontent.com/assets/6081912/4371616/f7ba7d06-4319-11e4-80e0-fc94ab551e95.png)
![2014-09-23 18 02 40](https://cloud.githubusercontent.com/assets/6081912/4371617/f7c2761e-4319-11e4-8bbd-d3f66e69789f.png)

**Comment by Garfield550** [comment]
感谢反馈， Emoji 符号问题我们已经知道了，修复需等 @biergaizi ，因为开发人员实在太少了

**Comment by biergaizi** [comment]
Duplicate: #129, #18
