### ISSUE TITLE
换个方式支持中文表情

### ISSUE THREAD

**Issue by farseerfc** [WeCase/WeCase#142]
因爲需要文件系統支持，也需要特定的LOCALE，偶爾會造成問題……
能否換個方式支持中文表情？

**Comment by biergaizi** [comment]
有道理，文件夹路径的确是个问题。这个可以 hack 一下，比如全都改成 ASCII 的 hash 啥的。

**Comment by biergaizi** [comment]
表情现在都在 tarball 里面了，不需要文件系统支持了。但 Unicode 支持还是要有的，既然是 Python 3 了就不会考虑纯 ASCII 兼容了。
