### ISSUE TITLE
未知 API 错误导致错误处理程序出现错误

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#148]
------------[ cut here ]------------

Version: WeCase 0.06-beta7-unknown

Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/WeCase/WeiboErrorHandler.py", line 43, in showAPIException
    error_message = self.ERRORS[int(exception.error_code)]
KeyError: 20112

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/WeCase/WeiboErrorHandler.py", line 45, in showAPIException
    error_message = "%d: %s" % (int(exception.error_code), exception.error)
AttributeError: 'CallerError' object has no attribute 'error'
---[ end trace 0xaf9572fc ]---

**Comment by biergaizi** [comment]
API 没法用了，全都 Permission Denied。

**Comment by Garfield550** [comment]
很多第三方都没法用了。包括迅雷开发的微博桌面在内，都出现了不能获取 AT 和 评论 的问题。Weico 还可以用，因为他的 API 是买的。

**Comment by biergaizi** [comment]
这里面有两个问题，第一个问题是 API 不让用了，返回 20112 错误；而第二个问题是这个 API 错误是未知错误，因此程序调用

```
error_message = "%d: %s" % (int(exception.error_code), exception.error)
```

却导致错误处理程序出现错误。

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    File "/usr/local/lib/python3/dist-packages/WeCase/WeiboErrorHandler.py", line 45, in showAPIException
    error_message = "%d: %s" % (int(exception.error_code), exception.error)
    AttributeError: 'CallerError' object has no attribute 'error'
```

因为我在写 rpweibo 的时候没有及时匹配这里的代码……第二个问题已经修复。

**Comment by biergaizi** [comment]
这个错误是 #146 的 duplicate。我当时已经修复错误了，然而却推送错了分支……

**Comment by Garfield550** [comment]
Get
