### ISSUE TITLE
建议升级 WeCase 授权方式

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#150]
使用官方推荐的授权页登录方式而不是模拟登陆

<s>省得官方没事找事</s>

**Comment by biergaizi** [comment]
准确的说这不是模拟登录，而是模拟登录授权页 (笑
要真能模拟登录还愁什么 API (笑

**Comment by Garfield550** [comment]
看看这个 http://weibo.com/1799644553/CddQLvCpS
