### ISSUE TITLE
自动认证方式改变，WeCase 已经无法登录

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#152]
也许是新浪对 API 进行了升级之类的，我倒有种猜测是新浪故意封闭了一下 API。

**Comment by biergaizi** [comment]
Confirmed.

**Comment by Garfield550** [comment]
我在刚才更新了下
App Secret：83822a8addf08cbcdaca75c76bec558a

**Comment by fwolf** [comment]
好像 IFTTT 连 Weibo 也不是很正常。

**Comment by xavieryao** [comment]
所以说咱们直接 POST 到 `https://api.weibo.com/2/oauth2/authorize` 的方法已经不行了？目测是 form 里那些校验参数起作用了

**Comment by xavieryao** [comment]
没错 POST 到 `https://api.weibo.com/2/oauth2/authorize` 的数据已经不包含 `userId` 和 `passWd` 而是预先换成 `ticket`

**Comment by Garfield550** [comment]
嗯，所以到现在，WeCase 已经废了

**Comment by xavieryao** [comment]
为何不用正常的 oauth ?

发自我的 iPhone

**Comment by Garfield550** [comment]
接口限制

**Comment by xavieryao** [comment]
盖子之前不是说发现了一个漏洞吗

发自我的 iPhone

**Comment by Garfield550** [comment]
但是不清楚这个有没有修啊，19号我问他吧

**Comment by biergaizi** [comment]
登陆？WeCase 是海军陆战队还是台风啊……

**Comment by Garfield550** [comment]
像台风一样飘忽不定

**Comment by biergaizi** [comment]
这么说渣浪就是太平洋了 :laughing:

**Comment by Garfield550** [comment]
对，淹死很多人

**Comment by biergaizi** [comment]
Fixed in https://github.com/WeCase/rpweibo/commit/7555d4e6064e7365bf760a4ea74330e1a6b48649.

**Comment by biergaizi** [comment]
目前没有处理带验证码的情况，不过基本问题已解决。
