### ISSUE TITLE
关于 WeCase 重构的讨论

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#156]
所有有关 WeCase 重构的讨论现在都在这个 Issues 进行。
重构讨论方向
1. 界面
2. API
3.  实现方式
4. ...

**Comment by Garfield550** [comment]
根据开源哥的建议，我们现在在实现方式上有了两种选择：
1. 继续使用 Python+PyQt
2. 使用 Lisp

**Comment by biergaizi** [comment]
其实编程语言方面可以不限。然而 WeCase 问题在于我当初脑残的架构设计，而编程语言完全是次要因素。架构还是个需要解决的问题。

**Comment by Garfield550** [comment]
来讲讲现在的架构

**Comment by 0312birdzhang** [comment]
建议继续使用 Python+PyQt,也希望开始网qml切换,增加跨平台的可移植性

**Comment by Garfield550** [comment]
会议并未如期举行

**Comment by biergaizi** [comment]
会议的组织工作交给 550 吧。

**Comment by Garfield550** [comment]
我在打工……

**Comment by senseab** [comment]
用go做后端，前端界面任意……RPC机制

**Comment by biergaizi** [comment]
目前的问题根本和编程语言完全无关，而是卡在了 RPC
机制的设计与实现上。最近虽然不是很忙，但也没有空闲到能一个个联系组织讨论的地步，有谁能帮帮忙那就十分感谢了……

**Comment by Garfield550** [comment]
我只能到 9 月才有空

**Comment by senseab** [comment]
我还是先理一下RPC机制可能的实现手段：
1. D-Bus
2. Unix Socket
3. TCP/IP Socket
4. HTTP（这TM用个毛线用）

**Comment by senseab** [comment]
不过消息的传递用json就可以了

**Comment by Garfield550** [comment]
@tonychee7000 你有时间组织开会吗？

**Comment by biergaizi** [comment]
@tonychee7000 

如果要前后端分离，我们就需要先定义概念
- 前端：数据显示和用户交互的平台，没有运算和处理能力
- 后端：对数据进行运算和处理的平台

那么作为后端，最大的任务就是要向渣浪 API 发送请求，然后 RPC 给前端。但现在最大的悖论在于，这样做着做着，不就等于给渣浪 API 又套了一层 API，结果无法解决任何 API 耦合导致的问题。

**Comment by senseab** [comment]
所以更是个大坑……

在 2015年08月21日 00:22, Tom Li 写道:

**Comment by 1a57danc3** [comment]
http://fanfou.com/apps.new

重新开始吗？

**Comment by Garfield550** [comment]
@ky0ncheng No

**Comment by biergaizi** [comment]
重新开始倒不是不行，但是首先要有能用的 API……

**Comment by Garfield550** [comment]
能也不搞了, 宁愿换 Twitter

**Comment by senseab** [comment]
I would like abandon this project for current weibo is all sh*t
