### ISSUE TITLE
path.py name conflict

### ISSUE THREAD

**Issue by zenithyr** [WeCase/WeCase#160]
archlinux + python3, compile from source and run wecase. I got msg below:

> wecase
> Traceback (most recent call last):
>   File "/usr/local/libexec/wecase.py", line 22, in <module>
>     from LoginWindow import LoginWindow
>   File "/usr/local/share/wecase/LoginWindow.py", line 14, in <module>
>     from WeCaseWindow import WeCaseWindow
>   File "/usr/local/share/wecase/WeCaseWindow.py", line 14, in <module>
>     from NewpostWindow import NewpostWindow
>   File "/usr/local/share/wecase/NewpostWindow.py", line 17, in <module>
>     from TweetListWidget import TweetListWidget, SingleTweetWidget
>   File "/usr/local/share/wecase/TweetListWidget.py", line 16, in <module>
>     from WAvatarLabel import WAvatarLabel
>   File "/usr/local/share/wecase/WAvatarLabel.py", line 10, in <module>
>     from WAsyncLabel import WAsyncLabel
>   File "/usr/local/share/wecase/WAsyncLabel.py", line 10, in <module>
>     from path import cache_path as down_path
> ImportError: cannot import name 'cache_path'

path.py refers to (https://pypi.python.org/pypi/path.py)

> python
> Python 3.5.0 (default, Sep 20 2015, 11:28:25) 
> [GCC 5.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > import path
> > > path.**file**
> > > '/usr/lib/python3.5/site-packages/path.py'

It's used by IPython, and seems to be shipped w/ arch's default python?

**Comment by cthbleachbit** [comment]
which branch are you on? `dev-0.06`?

**Comment by zenithyr** [comment]
Thanks for replying.

I tried both master & dev-0.06, neither works with traceback below:

~/test/WeCase-dev-0.06/build

> wecase 
> Traceback (most recent call last):
>   File "/usr/local/libexec/wecase.py", line 22, in <module>
>     from LoginWindow import LoginWindow
>   File "/usr/local/share/wecase/LoginWindow.py", line 14, in <module>
>     from WeCaseWindow import WeCaseWindow
>   File "/usr/local/share/wecase/WeCaseWindow.py", line 13, in <module>
>     from Notify import Notify
>   File "/usr/local/share/wecase/Notify.py", line 21, in <module>
>     class Notify(QtCore.QObject):
>   File "/usr/local/share/wecase/Notify.py", line 22, in Notify
>     image = path.icon_path
> AttributeError: module 'path' has no attribute 'icon_path'

**Comment by biergaizi** [comment]
Yes, it is a problem...
