### ISSUE TITLE
cant login weibo

### ISSUE THREAD

**Issue by csrgxtu** [WeCase/WeCase#162]
使用同样的帐户名密码可以在手机上登陆新浪微博，但是在WeCase里面登陆不进。

**Comment by biergaizi** [comment]
* Our API Key is expired.
* Much Restrictions to the OpenAPI has been added.
* Even the "Black Magic" key for the private APIs is not usable anymore.

It is almost impossible to develop a 3rd party client at all. This project has been suspended, and no one maintains it any more. 

Duplicate: #161.
