### ISSUE TITLE
access_token每次都会重新获取么？能否保存未过期的可用的access_token来自动登录

### ISSUE THREAD

**Issue by hetykai** [WeCase/WeCase#163]
access_token不是有一个有效期么，为何需要每次重新获取access_token呢？
可否获取一个access_token之后保存这个access_token，只要access_token还在有效期，频率限制没有超出，下次直接使用这个access_token来登陆呢？

**Comment by biergaizi** [comment]
当然可以。但当年尝试实现该功能时遇到了奇怪的问题。

反正现在已经不开发了……
