### ISSUE TITLE
“关于”窗口应该固定大小

### ISSUE THREAD

**Issue by biergaizi** [WeCase/WeCase#19]
“关于”窗口应该固定大小（Min 大小 = Max 大小），否则应该使用更合理的布局管理。
@tonychee7000 你改变下窗口大小，看看 Logo 都变成什么样了。

**Comment by senseab** [comment]
已经对AboutWindow固定大小（Fix & Min=Max）在AboutWindow分支

**Comment by biergaizi** [comment]
Fixed in b50a18bd68d6e3fbd82edd20af7511d5e442eebd
