### ISSUE TITLE
WeCase添加个表情功能

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#21]
手动输入"[表情名]"太麻烦了~囧

**Comment by cthbleachbit** [comment]
那么不是还得再加一个表情库么

**Comment by Garfield550** [comment]
@cthbleachbit 我在下载gif~

**Comment by Garfield550** [comment]
表情包已经准备好了：http://s.yunio.com/XFMPrw 
2. http://pan.baidu.com/share/link?shareid=387405&uk=3557859337
![2013-04-04 23:53:53 ](https://f.cloud.github.com/assets/3471836/340200/6cf7c2cc-9d49-11e2-9c81-4eec0b5696d4.png)
就是以上这些
@cthbleachbit @biergaizi @tonychee7000 
还有，这Bug解决了是吧~
![2013-04-05 01:05:11 ](https://f.cloud.github.com/assets/3471836/340220/ed06e27c-9d49-11e2-8f17-464b8fff9390.png)

**Comment by Garfield550** [comment]
[草泥马][神马][浮云][给力][围观][威武][熊猫][兔子][奥特曼][囧][互粉][礼物][爱你][鄙视][闭嘴][挤眼][害羞][吃惊][挖鼻屎][可怜][可爱][哈哈][嘻嘻][呵呵][泪][偷笑][亲亲][生病][太开心][懒得理你][右哼哼][左哼哼][嘘][衰][委屈][吐][失望][钱][睡觉][困][汗][思考][拜拜][馋嘴][疑问][怒][抱抱]

**Comment by biergaizi** [comment]
表情显示的大致思路和原型已经有了，用了 QML。这个特性几天之后就能加入程序了。

**Comment by biergaizi** [comment]
在 70fdce3c043f2a17ab1016f06acf1426db329ecd 中完工！
