### ISSUE TITLE
WeCaseLaunchpad页

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#22]
https://launchpad.net/~wecase

**Comment by biergaizi** [comment]
@Garfield550 私下给我管理权限。

**Comment by m13253** [comment]
求加入 membership，我的 Launchpad 账号是 m13253

**Comment by biergaizi** [comment]
@m13253
加入了，这回改成 Team 了：https://launchpad.net/~wecase
有邮件列表哦～
