### ISSUE TITLE
关闭窗口时程序没有结束

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#23]
在把“检查新微博”间隔调长后，程序不会在关闭主窗口后马上结束
![2013-04-05 20:44:58 ](https://f.cloud.github.com/assets/3353318/343904/af768764-9dee-11e2-9608-4587e13aaa3e.png)

终端里运行时感觉很明显，但打开py文件直接运行的没有太大影响，

**Comment by biergaizi** [comment]
这不是 bug，是技术限制。

**Comment by cthbleachbit** [comment]
求解释

**Comment by biergaizi** [comment]
我们来看看定时器的实现代码：

``` python
def run(self):
    while not self.stopped:
        time.sleep(self.sleep_time)
        self.run_function()
```

也就是说，在设置 `stopped` 为 `True` 之后，程序还在上一个 sleep 周期。
我目前还没有想出什么好的解决方法。

**Comment by cthbleachbit** [comment]
原来是这样，，，

**Comment by m13253** [comment]
可以这样：

``` python
def run(self):
    for i in range(4):
        if self.stopped:
            return
        time.sleep(self.sleep_time/4)
    self.run_function()
```

（刚刚代码写错了。更新了一下）

**Comment by biergaizi** [comment]
@m13253 <del> 空循环不好</del>
我打算用事件，很快推代码。

**Comment by biergaizi** [comment]
Fixed in 6d5f8fbbadf1e7c0b5db55285d85c7a32aa9fc0a

**Comment by Garfield550** [comment]
我勒个去……
