### ISSUE TITLE
Readme 里没有写明完整的依赖

### ISSUE THREAD

**Issue by m13253** [WeCase/WeCase#24]
Readme 里没有写明完整的依赖，导致 Linux 吧一群小白问为什么无法启动。
我的 ArchLinux 包里面的依赖是这么写的：
`依赖于　　： python>=3  pyqt>=4  python-dateutil  python-notify2`

**Comment by biergaizi** [comment]
很好。
现在的问题是，各个发行版依赖不太一样，名字很不好找，而且同是 Debian 系，居然有的没有 `python3-dateutil`。因此，`notify2` 很多发行版也没包。

因此现在首要目标，就是这这两个包打包，然后打包 WeCase。我们已经有 Launchpad 首页了。然后是 Fedora，我还有不少 Fedora 情结……

另外我打算自己实现时间戳的转换，下个版本移除这个依赖。

**Comment by m13253** [comment]
你最好先保证 Readme 里面写明白了所有依赖。不要等着用户自己运行发现缺少依赖的时候才装……

**Comment by biergaizi** [comment]
只要不是涉及核心问题，这里的代码你随便改，不用等我效率底下的行动。

**Comment by biergaizi** [comment]
Fixed in 9d9f46f147a5a859bea51f7aa2871292fa4c30b5 and c1c222c.

**Comment by m13253** [comment]
貌似 WeCase 现在不依赖 `python-requests`。是否需要从 README 里面删掉？

**Comment by biergaizi** [comment]
据 @Garfield550 所说，`python-requests` 在 Ubuntu 中被 `urllib` 隐性依赖……
