### ISSUE TITLE
JavaScript 字数统计函数有时返回 NaN

### ISSUE THREAD

**Issue by biergaizi** [WeCase/WeCase#26]
输入

```
哈哈，今天写了不少代码啊 http://github.com/WeCase/WeCase/commits/experimental
```

即可重现。

**Comment by cthbleachbit** [comment]
"http://"字符串引起的，删掉其中任意字符就会恢复正常
![ _001](https://f.cloud.github.com/assets/3353318/346974/8cc2e87a-9e84-11e2-8e3e-75745c0cb9c6.png)

**Comment by biergaizi** [comment]
@cthbleachbit 这个我知道，不用你告诉我。
关键的问题是新浪的那个字数统计函数，太恶心了，根本读不懂。还需要研究一段时间。

**Comment by cthbleachbit** [comment]
好吧，加油

**Comment by biergaizi** [comment]
在这里，你可以看看：https://github.com/WeCase/WeCase/blob/experimental/ui/JavaScript.qml

**Comment by biergaizi** [comment]
Fixed in 363e421047d88d5b5a80230df863104c5c4f7185
