### ISSUE TITLE
WeCase新ICON

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#28]
![wecase192](https://f.cloud.github.com/assets/3471836/347045/90ec0478-9e92-11e2-972a-b6e0605c64ae.png)

**Comment by Garfield550** [comment]
http://pan.baidu.com/share/link?shareid=389719&uk=3557859337

**Comment by 1a57danc3** [comment]
我按错了。。。

**Comment by Garfield550** [comment]
@kawaiiushio 你把 @biergaizi 的话删掉了？

**Comment by biergaizi** [comment]
好像就是这样的

**Comment by Garfield550** [comment]
@biergaizi 他说这个ICON不好看~

**Comment by biergaizi** [comment]
那就弄 N 个方法慢慢挑吧

**Comment by Garfield550** [comment]
我也点错了……今天怎么了~

**Comment by Garfield550** [comment]
@biergaizi 
图传不上来~

**Comment by biergaizi** [comment]
世界手贱日……今天我提交 Git 的时候也手贱了，你没看到 Revert 吗T_T

**Comment by Garfield550** [comment]
哦，好吧~

**Comment by biergaizi** [comment]
什么图？

**Comment by Garfield550** [comment]
http://ww4.sinaimg.cn/large/6f6fa1e9tw1e3gar7ou2sj.jpg
这是 @kawaiiushio 做的

**Comment by Garfield550** [comment]
我看着想到了塞班！

**Comment by Garfield550** [comment]
@biergaizi

**Comment by biergaizi** [comment]
手贱把我没法出去的评论删了

**Comment by Garfield550** [comment]
……你删掉了？ @biergaizi

**Comment by biergaizi** [comment]
其实这两个图都挺别扭。你应该在微博上来次设计方案的头脑风暴，当然把大家引导在这里讨论。P.S：输入拼音 liang g，第一个候选词我晕了。

**Comment by 1a57danc3** [comment]
刚刚点错 抱歉
![wecase](https://f.cloud.github.com/assets/2175497/347420/5de6705a-9ecd-11e2-9276-959d3bf7a046.png)

**Comment by Garfield550** [comment]
两个 没删么区别啊~两个，，，我的是这样 @biergaizi

**Comment by 1a57danc3** [comment]
PREVIEW ONLY

**Comment by Garfield550** [comment]
@kawaiiushio 你这渐变还是加光？不合适啊

**Comment by 1a57danc3** [comment]
渐变

**Comment by Garfield550** [comment]
真心不合适，，，等我弄一个征求图标意见的微博吧~ @kawaiiushio

**Comment by Garfield550** [comment]
@biergaizi  @kawaiiushio  大概明天或者下个星期可以弄那个微博~要不弄一次设计比赛奖励个50元话费怎样？

**Comment by biergaizi** [comment]
感觉目前见到的 Logo 没一个合适的。赶紧去微博头脑风暴啊。囧rz  P.S：猜出我的候选词了吗T_T

**Comment by biergaizi** [comment]
五十元话费？经费谁出？

**Comment by Garfield550** [comment]
两根？ @biergaizi  话费我出~可以？

**Comment by biergaizi** [comment]
没问题，社区大使以后就是你了。P.S：出来的词 @kawaiiushio 应该能猜到

**Comment by Garfield550** [comment]
@biergaizi 哦

**Comment by Garfield550** [comment]
http://tieba.baidu.com/p/2255107350

**Comment by Garfield550** [comment]
http://tieba.baidu.com/p/2255111614

**Comment by 1a57danc3** [comment]
T-T

2013/4/6 Garfield550 notifications@github.com

**Comment by Garfield550** [comment]
我真是个奇葩……难看吗？
@biergaizi 
@kawaiiushio 
@m13253 
@cthbleachbit 
@WeCase 
![ 1](https://f.cloud.github.com/assets/3471836/437653/decdfba0-b0a9-11e2-8886-9fdf478580ec.png)

**Comment by Garfield550** [comment]
![ 2](https://f.cloud.github.com/assets/3471836/437695/fe143b7c-b0aa-11e2-9417-09b37dccf1d4.png)

**Comment by cthbleachbit** [comment]
不错。

By CTH via iPad

**Comment by m13253** [comment]
还是原来的Wc好看……

**Comment by Garfield550** [comment]
@cthbleachbit 哪一个？
@m13253 哪一个？

**Comment by m13253** [comment]
在 2013-4-29，17:18，@Garfield550 写道：

> @m13253 哪一个？

我还是喜欢现在的红色Wc图标，干脆别换了吧。

**Comment by Garfield550** [comment]
@m13253 ……

**Comment by m13253** [comment]
我建议现在别换，Wc反而会引起别人的好奇心来尝试这款软件。
建议等WeCase做大了，有知名度了，再弄一个图标征集大赛。

**Comment by 1a57danc3** [comment]
wordpress即视感

在 2013年4月29日下午6:25，Star Brilliant notifications@github.com写道：

**Comment by biergaizi** [comment]
Wordpress 既视感 +1.
我也建议更换图标计划暂时冻结。

有别的意见吗？不然我直接关掉这个 bug 了。
