### ISSUE TITLE
在搞图标设计大赛前，还是先讨论下怎么举行吧~

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#29]
我打算这个周末~
怎么举行
图标的设计要求
还有其他的一些事项
都来讨论讨论

**Comment by cthbleachbit** [comment]
svg？

By CTH via iPad

**Comment by Garfield550** [comment]
@cthbleachbit 必须的

**Comment by Garfield550** [comment]
投票都不理想
Windows7吧为14:4
![2013-04-08 12:26:14 ](https://f.cloud.github.com/assets/3471836/350048/b0463eba-a004-11e2-918c-f61acb7bf806.png)
Linux吧为18:18
![2013-04-08 12:26:03 ](https://f.cloud.github.com/assets/3471836/350051/bfbb33a0-a004-11e2-951a-19117a486e9c.png)
微博为23:34
![2013-04-08 12:28:48 ](https://f.cloud.github.com/assets/3471836/350052/de801738-a004-11e2-915b-d6702e09d5ef.png)
@biergaizi  @kawaiiushio

**Comment by biergaizi** [comment]
:1234: 
我晕，居然是 1:1 的比例……

**Comment by Garfield550** [comment]
:8924:
:1234:

**Comment by m13253** [comment]
不限制设计要求，但是要求必须以 CreativeCommons 或兼容协议发布。

还有，那个蓝色 Wc 图标可能在 Ubuntu 的 Dock 栏里显示效果不好（双重边框）

**Comment by biergaizi** [comment]
CC 协议倒是必须的，不用担心。

**Comment by m13253** [comment]
那就可以了啊。没有设计要求，如果设计不好显然投票不高。这就是隐性设计要求。

**Comment by Garfield550** [comment]
好

**Comment by Garfield550** [comment]
@biergaizi 
@m13253 
@cthbleachbit 
@kawaiiushio 
帮忙想些话
对，是活动需要的“话”
![ ](https://f.cloud.github.com/assets/3471836/406066/c0317220-aa51-11e2-8682-3e58e8517011.png)
