### ISSUE TITLE
无法保存登录信息

### ISSUE THREAD

**Issue by m13253** [WeCase/WeCase#31]
登录时勾选「自动登录」，第二次仍然提示登录，发现 `.config/wecase` 下没有存储内容。

还有问题是。勾选「自动登录」会自动勾选「记住我」，这个实现了；但是取消「记住我」的时候应该同时取消「自动登录」，这个却没有实现。

**Comment by biergaizi** [comment]
实际上登录窗口保存功能坏了，连「记住我」都失效了。

**Comment by biergaizi** [comment]
Fixed in 502d514.
