### ISSUE TITLE
添加图片的扩展名问题

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#33]
![ _001](https://f.cloud.github.com/assets/3353318/376579/c3db4b50-a441-11e2-9845-046399339f28.png)
图片选项没有包含png文件，上传有点小麻烦

**Comment by biergaizi** [comment]
是有的。可能是本地化导致行为不是预期的。

**Comment by biergaizi** [comment]
你再看看。

**Comment by cthbleachbit** [comment]
已解决
