### ISSUE TITLE
断网登录时没有错误提示

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#36]
![ _001](https://f.cloud.github.com/assets/3353318/414188/efce8f5e-ac0e-11e2-8899-1e77928c5e8c.png)
如图，在terminal能看到，直接运行就木有了，希望加一个弹出提示

**Comment by Garfield550** [comment]
哦，这的确是一个没有考虑到的问题

**Comment by biergaizi** [comment]
这个问题设计之初就考虑到了，但是那时候由于要避免过度设计暂时没有实现，然后就再也忘了，别人还认为我是马后炮。WeCase 好多其它的细节问题也是这样。

这个问题怎么破？

**Comment by biergaizi** [comment]
Fixed in 3bfaf6e3c1252b4463c22d088d5046d91ce6489b.
