### ISSUE TITLE
中英的README

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#37]
改一下README.md吧，中国人访问的时候，方便～

**Comment by cthbleachbit** [comment]
已在 2426252 中添加

**Comment by Garfield550** [comment]
你没有把新README.md合并到master

**Comment by biergaizi** [comment]
@Garfield550 我强调过许多次了，任何并入 `Master` 的操作都必须我亲自进行，就像 Linux 的 `Torvalds` 分支一样；新增版本 `tag` 需要附带我的 GPG 签名，否则视为源码库被入侵。
