### ISSUE TITLE
ubuntu13.04安装后没有图标

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#38]
![2013-05-10 12 59 21](https://f.cloud.github.com/assets/3471836/486637/a9101ff6-b92e-11e2-9cd3-a046482af75c.png)

他的版本未知，请
@kawaiiushio 检查一下

**Comment by biergaizi** [comment]
告诉他，WeCase 没有安装程序。不存在什么污染系统，也不知道他是怎么“安装”的。
