### ISSUE TITLE
刷新后没有更新之前的微博的时间戳

### ISSUE THREAD

**Issue by m13253** [WeCase/WeCase#39]
我安装的版本是 1e7507f478c75cbb21d34563f8a8d8e031092c5d 。
见图，我点击刷新前最新的是第二条微博，刷新后刷出来一条新微博。但是第二条微博的时间戳没有更新。
我觉得解决方案应该是，每隔15秒或每次点击刷新时，更新所有时间戳。（个人觉得15秒比较合理）
![50c3208e-c347-41fe-a677-30f9b1488058](https://f.cloud.github.com/assets/1808930/549464/e2241250-c2f9-11e2-8914-605c573045ff.png)

**Comment by biergaizi** [comment]
这也是一个技术限制，没有优雅的办法，所以就没弄。而且 QML 很快就要被我废弃了，不管它了。

**Comment by Garfield550** [comment]
我都不管他的

**Comment by biergaizi** [comment]
Fixed in Developing version: f611277b76a45ee76f2951a374f84d5c8e090e38
