### ISSUE TITLE
主窗口最小宽度时元素重叠

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#41]
![_001](https://f.cloud.github.com/assets/3353318/563808/bfce8e96-c516-11e2-9377-e6db7df53e96.png)

如图，头像与图片重叠。

**Comment by biergaizi** [comment]
听不懂你在说什么，哪里重叠了？

**Comment by cthbleachbit** [comment]
现在有了

**Comment by biergaizi** [comment]
好吧，其实这个 Bug 是一个坑，来自于 @tonychee7000 的计算缩略图位置的代码，从 0.01 就有。后来我懒得改，一直保留至今。哪怕是界面重新实现了，策略依然没变。

下个版本修复吧，到时候也不用 QML 了。

**Comment by biergaizi** [comment]
Fixed in Developing Version 0.06: ca2e33931de536f1f02505522c0d405ee107622b
