### ISSUE TITLE
0.06 到底应该是 tag 还是 branch？

### ISSUE THREAD

**Issue by m13253** [WeCase/WeCase#42]
发现 0.06 branch，而不是 tag。
这是怎么回事？是一个 experimental branch 还是误操作？
话说我已经把 0.06 推到 AUR 源了啊……
如果 0.06 branch 是稳定代码，请合并到 master，删除分支并创建 tag；
如果是实验性代码，我只好在 AUR 源降级了……（用`yaourt -Syua`是无法降级的，降级需要两个`-uu`，这就意味着已经安装 0.06 版本的人可能不会自动降级）

还有以后创建了新 tag 请自觉到我的 [AUR 页面](https://aur.archlinux.org/packages/wecase/) 去点击 Flag Out-Of-Date，不要让我每次都来检查你这边，结果这次还弄出问题了……

**Comment by biergaizi** [comment]
F__K! 看清楚点！0.06 是 0.06 版本的开发分支啊！请立刻降级！
任何时候，`master` 是且只是唯一的稳定分支，

**Comment by m13253** [comment]
那你倒是写清楚啊，比如 dev-0.6 啊……
我只是自动检测 GitHub 上是否存在 0.6.tar.gz 的代码包，有就会更新 PKGBUILD……
