### ISSUE TITLE
增加清除缓存

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#44]
WeCase用久了
~/.cache/wecase里有很多图片，
尽管`rm -rf`可以做到，但对于小白们可能是个坑啊

**Comment by 1a57danc3** [comment]
rm -rf */  小白必备指令

**Comment by biergaizi** [comment]
@kawaiiushio 应该是 `rm -rf /` 吧……

**Comment by 1a57danc3** [comment]
[?]

**Comment by biergaizi** [comment]
Fixed in edffe37.
