### ISSUE TITLE
设定窗口的对话框

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#47]
即使我没有改动过滤设置，点击确定时仍然会提示需要重新打开WeCase来应用过滤规则，

**Comment by biergaizi** [comment]
是否改动过滤设置的判断代价太大……刻意不作处理。Fcitx 的 KDE 配置还天天玩命提示呢。

**Comment by biergaizi** [comment]
Fixed in 4802bed61c8a1fbab8946dd5190f73e4ca333df3.
