### ISSUE TITLE
托盘功能

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#59]
ubuntu unity狂戳托盘图标没有任何反应是什么情况

**Comment by biergaizi** [comment]
不要向开发分支报告 Bug。不过 Ubuntu 这个值得引起注意。

**Comment by biergaizi** [comment]
你试试最新的开发版？

**Comment by cthbleachbit** [comment]
没有用
![_001](https://f.cloud.github.com/assets/3353318/825787/c45faf64-f075-11e2-8fc6-cd4de981d053.png)
所需要的效果类似于上图

**Comment by librehat** [comment]
Fedora 19, KDE，
已安装好依赖关系和python3的notify2包（从源码安装的）。所以应该不是依赖关系的问题，
KDE的托盘里没有WeCase哦

**Comment by biergaizi** [comment]
@librehat  F__k，请使用开发分支。

**Comment by biergaizi** [comment]
另外

> KDE的托盘里没有WeCase哦

这种语气报告 Bug？恶意卖萌？

**Comment by librehat** [comment]
Sorry. :-(

另外……这真的是在卖萌么？..>_<..

**Comment by biergaizi** [comment]
@librehat 你把“哦”去掉，感觉就好了…… ^_^

**Comment by biergaizi** [comment]
Fixed in https://github.com/WeCase/WeCase/commit/f0bcf2bd05c5b2aacc0eeff3f68eed327e6f5ddc.

@cthbleachbit Please test it.
