### ISSUE TITLE
界面布局

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#60]
![_001](https://f.cloud.github.com/assets/3353318/831718/d91ba47c-f209-11e2-9f3b-f0994da793c4.png)
不仅如此，小窗口还能自动停靠在窗口四边。

**Comment by cthbleachbit** [comment]
![_001](https://f.cloud.github.com/assets/3353318/831734/3c7b2da2-f20b-11e2-95db-d9e7e3bb4b0b.png)
还有这样的，我总觉的是界面布局问题

**Comment by Garfield550** [comment]
好吧……
![- 20130722 - 041133](https://f.cloud.github.com/assets/3471836/832272/c760d6de-f241-11e2-8a93-b080235d3fce.png)

**Comment by cthbleachbit** [comment]
我觉得ubuntu这样反而是可定制了，，哪里爽放哪里

**Comment by biergaizi** [comment]
嗯，Ubuntu 实在是无语……

这按钮看来不能放在标题栏……

**Comment by biergaizi** [comment]
另外，刚打开程序的时候，这两个按钮是什么样子的？能发个图吗？

**Comment by cthbleachbit** [comment]
刚打开么，
![_001](https://f.cloud.github.com/assets/3353318/877116/4add60ce-f8e9-11e2-8305-51ce10f9ffaa.png)

**Comment by biergaizi** [comment]
@cthbleachbit 经过 https://github.com/WeCase/WeCase/commit/45a546351cbc52582cf54e8f0533a8882a517044 和 https://github.com/WeCase/WeCase/commit/d53dbaeaf0f615cb51ee0afbae8998dbcd5a4ba8, 请再看看 Ubuntu 上是什么效果……

**Comment by biergaizi** [comment]
这个作为 **blocker** 了，影响太大。

**Comment by biergaizi** [comment]
Ubuntu 下这两个按钮会动的原因找到了，原来 Ubuntu 还挺聪明，将 `menuBar()` 去除后，原来的 `cornerWidget()` 自动会变为 `QToolBar()` 处理，这样程序也不会 break，好评 —— 于是就能拖动了。

那我就干脆给 Ubuntu 好好做个 Toolbar 好了。

**Comment by cthbleachbit** [comment]
其实我就觉得本来那个toolbar就不错，，

在 2013-8-7，下午9:41，Tom Li notifications@github.com 写道：

**Comment by biergaizi** [comment]
![WeCase in Ubuntu](https://f.cloud.github.com/assets/1310693/926012/8f3ebeb6-ff83-11e2-958a-9f8aef4b8695.png)

暂且这样了。

**Comment by biergaizi** [comment]
相关的两个提交是 https://github.com/WeCase/WeCase/commit/7ce94f40c950e65cd43c7295eab800be1d4566f7 和 https://github.com/WeCase/WeCase/commit/780b7430b0539c22b0d2844c987701c2ba9827eb.

**Comment by cthbleachbit** [comment]
ok
