### ISSUE TITLE
表情库不完整

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#61]
表情库不完整，导致部分表情无法显示。

![- 20130722 - 045023](https://f.cloud.github.com/assets/3471836/832324/772f50cc-f247-11e2-8553-28b2940b37ef.png)

**Comment by biergaizi** [comment]
知道了，很快处理。

**Comment by biergaizi** [comment]
Bug -> Enhancement

**Comment by biergaizi** [comment]
Fixed in c2494cf2693bcdde8ae48f58f28e0188a2c5cfcd. What a large change!
