### ISSUE TITLE
无法播放动态表情

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#67]
![_001](https://f.cloud.github.com/assets/3353318/876185/455f0916-f8be-11e2-9e2d-733d3e936227.png)
有的爱心只有半个是怎么回事。。。。

**Comment by biergaizi** [comment]
因为这是个动画，但是不能放。

**Comment by cthbleachbit** [comment]
怎么有的显示的出来

**Comment by biergaizi** [comment]
因为有的表情第一帧的画面是完整的

**Comment by cthbleachbit** [comment]
well,then

**Comment by biergaizi** [comment]
Fixed in https://github.com/WeCase/WeCase/commit/681e7552a7c05c9143c18523587fae50f81f71e5.
