### ISSUE TITLE
点图片时触发错误

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#68]
有时点击图片会重现，，

并给出一个[很长的错误信息](https://gist.github.com/cthbleachbit/6110009)

有900行左右，，，，

同时无法打开图片

**Comment by biergaizi** [comment]
无限递归

**Comment by cthbleachbit** [comment]
any idea

**Comment by biergaizi** [comment]
Fixed in https://github.com/WeCase/WeCase/commit/4434bc5fa9846b1ca9dd4f062178f74373db8fc7.
Test needed.
- maybeFixed

**Comment by cthbleachbit** [comment]
bug still exists
- -maybefixed

**Comment by cthbleachbit** [comment]
在arch里装好了pinyin，，舒服多了
![snapshot1](https://f.cloud.github.com/assets/3353318/876885/32906bb8-f8e1-11e2-9533-946e5289fc7e.png)

**Comment by biergaizi** [comment]
又尝试修复了，你再看看。

**Comment by cthbleachbit** [comment]
暂且没有问题，还需观察。
- MaybeFixed

**Comment by biergaizi** [comment]
根据第七次会议讨论，此问题认定为解决。
- fixed
