### ISSUE TITLE
再点击一张图片，曾经点击过的图片菊花全都集体进击……

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#74]
点击图片时图片可以打开，但是图片打开之后菊花还在转

**Comment by biergaizi** [comment]
共享内存问题。

**Comment by biergaizi** [comment]
具体描述是，点击一个图片，菊花出现。图片打开后，菊花消失。这时再打开另一张图片，曾经消失的菊花会在所有图片中出现。

**Comment by cthbleachbit** [comment]
不是，，，

**Comment by cthbleachbit** [comment]
点击图片，菊花出现，图片打开后，菊花还在，，，

**Comment by biergaizi** [comment]
这一定是在你打开第二张图片时才发生的……

**Comment by biergaizi** [comment]
**我的猜测没错，已经验证了。**

整个程序仅仅使用一个 `busyMovie`（Movie 代表会动的一切，包括 `gif`）来代表菊花。

当点击图片后，`busyMovie.start()` 开始播放。同时，把信号 `frameChanged` 与绘制菊花的槽函数连接起来，每次 `busyMovie` 播放到下一帧时，重绘图片，合成菊花。我们就可以看到菊花转动的动画效果的 —— 其实就是逐帧绘制。

图片加载完后，使用 `busyMovie.stop()` 来使动画停止，同时将之前保存的原图重新加载，图片就恢复正常了。

关键的问题时，整个程序中**只有一个** `busyMovie()`。这张图片里停止了 `busyMovie()`，别的图片里却又播放了 `busyMovie()`，同时，由于槽函数的连接只有在点击过的图片中才会发生 ——

**所以你观察到的现象就是，点击过的图片菊花明明已经消失了，再点击另一张图片，这时候点击过图片的菊花都进击了……**

**Comment by biergaizi** [comment]
解决这个问题最简单的方法就是，在图片加载完成后，不要仅仅停止 Movie，还要断开信号和槽的连接，这样无论这个  Movie 再怎么动，图片根本都不会鸟它。
