### ISSUE TITLE
密码存放安全

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#76]
`~/.config/wecase/config_db`中使用明文密码有没有风险

**Comment by biergaizi** [comment]
不只是 WeCase 这么做，所有的“记住密码”实现都是明文密码，包括 Chrome 和 Firefox。

我认为这不是一个太大的问题，因为： 
1. 所有安全问题的前提都是物理安全，如果你的机器物理上就是不安全的，那即使给你变成星号了你的密码也不会安全； 
2. 如果物理上是安全的，也就是说接触你的电脑的人是可信的，那即使是明文保存的他也不会特地去看；
3. 如果物理上是不安全的，接触你电脑的人有破解密码的决心，那么无论采用什么安全措施，只要源代码公开就没有任何秘密可言。

总而言之，客户端的这点防盗功能永远是防君子不防小人，重点是物理安全。

**Comment by biergaizi** [comment]
@cthbleachbit 这个问题在项目开始的第一天就讨论过了，你这么挖坟我已经受不了了。

**Comment by biergaizi** [comment]
未来如果需要，可以考虑使用 KWallet 和 Gnome Keyring 保存密码，不过现阶段暂无计划。

而且，极度讨厌这种 Keyring 的用户不少啊。

**Comment by cthbleachbit** [comment]
抱歉，，
