### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by biergaizi** [WeCase/WeCase#79]
```
libpng warning: iCCP: known incorrect sRGB profile
```

这个警告虽然可以无视，也没有后果。但是这说明一些图片的标准过时了，简单转换一下即可。

**Comment by biergaizi** [comment]
很简单，首先需要下载一个 `sRGB_v4_ICC_preference.icc`。

然后，`for x in *png; do convert $x -profile sRGB_v4_ICC_preference.icc $x; done`。

**Comment by sunkehappy** [comment]
这个还得需要先下载安装ImageMagick吧？

**Comment by biergaizi** [comment]
是的。
