### ISSUE TITLE
通知提醒不会在浏览之后清零

### ISSUE THREAD

**Issue by biergaizi** [WeCase/WeCase#8]
收到通知，阅读之后。提醒应当调用 `remind/set_count` 接口清零。
这个特性正在实现中，记录在此。

**Comment by biergaizi** [comment]
需要申请权限才能使用 `remind/set_count`，因此请  @Garfield550 (CC  @WeCase/owners @WeCase/committers) 尽快将应用送审并申请高级授权。

**Comment by cthbleachbit** [comment]
新浪的设定很不人性化啊

**Comment by biergaizi** [comment]
此问题已在 23347b4747f1a664dda913f8cfdb285a136d159e 时被修复，并在 dd50e477a89259f05a061283903500f9a912987d 时被完善。

**Comment by Garfield550** [comment]
Good job
