### ISSUE TITLE
dbus某未知错误

### ISSUE THREAD

**Issue by chrt** [WeCase/WeCase#82]
环境: 

> $ uname -a
> Linux myArch 3.10.5-1-ARCH #1 SMP PREEMPT Mon Aug 5 08:53:16 CEST 2013 i686 GNU/Linux

输入用户名、密码后，点击“走起”，提示如下:

> Traceback (most recent call last):
>   File "/usr/lib/python3.3/site-packages/dbus/bus.py", line 175, in activate_name_owner
>     return self.get_name_owner(bus_name)
>   File "/usr/lib/python3.3/site-packages/dbus/bus.py", line 361, in get_name_owner
>     's', (bus_name,), **keywords)
>   File "/usr/lib/python3.3/site-packages/dbus/connection.py", line 651, in call_blocking
>     message, timeout)
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/WeCase/src/LoginWindow.py", line 79, in checkLogin
>     self.accept()
>   File "/usr/lib/WeCase/src/LoginWindow.py", line 49, in accept
>     wecase_main = WeCaseWindow()
>   File "/usr/lib/WeCase/src/WeCaseWindow.py", line 59, in **init**
>     self.notify = Notify(timeout=self.notify_timeout)
>   File "/usr/lib/WeCase/src/Notify.py", line 24, in **init**
>     pynotify.init(appname)
>   File "/usr/lib/python3.3/site-packages/notify2.py", line 96, in init
>     '/org/freedesktop/Notifications')
>   File "/usr/lib/python3.3/site-packages/dbus/bus.py", line 241, in get_object
>     follow_name_owner_changes=follow_name_owner_changes)
>   File "/usr/lib/python3.3/site-packages/dbus/proxies.py", line 248, in **init**
>     self._named_service = conn.activate_name_owner(bus_name)
>   File "/usr/lib/python3.3/site-packages/dbus/bus.py", line 180, in activate_name_owner
>     self.start_service_by_name(bus_name)
>   File "/usr/lib/python3.3/site-packages/dbus/bus.py", line 278, in start_service_by_name
>     'su', (bus_name, flags)))
>   File "/usr/lib/python3.3/site-packages/dbus/connection.py", line 651, in call_blocking
>     message, timeout)
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

**Comment by biergaizi** [comment]
Duplicate Bug for #70. See comment 3. It seems a issue cause by system notify framework itself, no known solution.

**Comment by biergaizi** [comment]
@chrt What is your desktop environment?

**Comment by biergaizi** [comment]
I just found out the explain of the issue.

WeCase requires a notification server[1]. If you're using a desktop environment other than GNOME or KDE, you need to configure your session manager to launch "/usr/lib/notification-daemon-1.0/notification-daemon" on login[2], or install xfce4-notifyd or notify-osd.

[1] https://wiki.archlinux.org/index.php/Libnotify
[2] https://wiki.archlinux.org/index.php/Autostarting

**Comment by biergaizi** [comment]
Finally, thanks for reporting. I'll add some detection code for this situation. Try to follow the guide to install a notification-daemon, then tell me if you succeed.

**Comment by chrt** [comment]
@biergaizi Thank you very much. Now I can use it normally. My desktop environment is xfce and I installed xfce4-notifyd.
