### ISSUE TITLE
WeCase上游原版点击评论按钮出现错误

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#83]
当在WeCase窗口点击评论按钮，如果获取到的评论有自己发表的评论时会触发下图错误。

![- 20130915 - 113437](https://f.cloud.github.com/assets/3471836/1144647/4c6bb17c-1db8-11e3-80ab-84f7fbdea760.png)

**Comment by biergaizi** [comment]
**不要** 报告 dev 版本的错误！dev 版本本来就是有已知问题，或未完成开发的半成品。只能报告 experimental 版本的 Bug。

**Comment by biergaizi** [comment]
Fixed.
