### ISSUE TITLE
刷新动画不会消失

### ISSUE THREAD

**Issue by Garfield550** [WeCase/WeCase#84]
当在任意一个页面点击一次刷新按钮时，刷新进程结束但图标不会消失

![- 20130915 - 112752](https://f.cloud.github.com/assets/3471836/1144653/e1d7e636-1db8-11e3-851e-a45867d94388.png)
![- 20130915 - 114236](https://f.cloud.github.com/assets/3471836/1144654/e6fd295a-1db8-11e3-883d-8c0aeb97d608.png)

**Comment by biergaizi** [comment]
**不要** 报告 dev 版本的错误！dev 版本本来就是有已知问题，或未完成开发的半成品。只能报告 experimental 版本的 Bug。

**Comment by biergaizi** [comment]
Fixed.
