### ISSUE TITLE
登录窗口的提示需要优化

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#89]
根据我亲戚的反馈，，
“用户名”最好改成"邮箱或手机号"，否则某些用手机号注册的要不知所措了

**Comment by cthbleachbit** [comment]
translation required

**Comment by biergaizi** [comment]
WTF. What are you doing... Reverted.

**Comment by Garfield550** [comment]
为什么不能是油箱君或手机君
----- 原始邮件 -----
发件人：James Chai notifications@github.com
收件人：WeCase/WeCase WeCase@noreply.github.com
主题：[WeCase]_登录窗口的提示需要优化_(#89)
日期：2013年10月07日 14点18分

**Comment by biergaizi** [comment]
Translation Updated in: dc1edada06295ad62cf4e5b66e24117c59f93e70.

Closing. More discuss should move to #55.
