### ISSUE TITLE
kubuntu下，使用window menubar组件后，刷新按钮消失

### ISSUE THREAD

**Issue by senseab** [WeCase/WeCase#91]
![image](https://f.cloud.github.com/assets/2174238/1287320/111d0de4-2ff3-11e3-87dd-b0af42edf622.png)
如图所示

**Comment by cthbleachbit** [comment]
kubuntu怎么长成这样，，，看来我又要装一个新的虚拟机了。。

**Comment by biergaizi** [comment]
知道了，得需要修改一下工具栏判定规则了……

**Comment by biergaizi** [comment]
@tonychee7000 帮我看看 Kubuntu 下有没有这些变量，值是多少：

```
$DESKTOP_SESSION
$UBUNTU_MENUPROXY
$APPMENU_DISPLAY_BOTH
```

**Comment by senseab** [comment]
$DESKTOP_SESSION=kde-plasma
剩下两个没有

**Comment by biergaizi** [comment]
@tonychee7000 再看看 Python 下

``` python
import platform
print(platform.linux_distribution())
```

的输出

**Comment by senseab** [comment]
('Ubuntu', '13.10', 'saucy')

**Comment by biergaizi** [comment]
应该修好了。

**Comment by senseab** [comment]
改天试，困死

**Comment by Garfield550** [comment]
原来你还没睡
----- 原始邮件 -----
发件人：TonyChyi notifications@github.com
收件人：WeCase/WeCase WeCase@noreply.github.com
主题：Re:_[WeCase]_kubuntu下，使用window_menubar组件后，刷新按钮消失_(#91)
日期：2013年12月28日 23点00分

**Comment by Garfield550** [comment]
明明 0:30 了。渣浪服务器怎么了...

原来是写的原始邮件发送时间...
