### ISSUE TITLE
Kubuntu make install后运行报错

### ISSUE THREAD

**Issue by senseab** [WeCase/WeCase#92]
**使用Kubuntu make install 后（./configure --prefix=/home/tonychyi/wecase/bin;make;make install）运行wecase开设置窗口报错**

---

> root        : ERROR    Oops, there is an unexpected error,
> Please report it at https://github.com/WeCase/WeCase/issues
> 
> Traceback (most recent call last):
>   File "/home/tonychyi/Wecase/bin/lib/python3.3/site-packages/WeCase/WeCaseWindow.py", line 480, in showSettings
>     wecase_settings = WeSettingsWindow()
>   File "/home/tonychyi/Wecase/bin/lib/python3.3/site-packages/WeCase/SettingWindow.py", line 22, in **init**
>     self.setupUi(self)
>   File "/home/tonychyi/Wecase/bin/lib/python3.3/site-packages/WeCase/SettingWindow.py", line 29, in setupUi
>     self.showSize()
>   File "/home/tonychyi/Wecase/bin/lib/python3.3/site-packages/WeCase/SettingWindow.py", line 32, in showSize
>     self.cacheSizeLabel.setText(self.getHumanReadableCacheSize())
>   File "/home/tonychyi/Wecase/bin/lib/python3.3/site-packages/WeCase/SettingWindow.py", line 35, in getHumanReadableCacheSize
>     raw_bytes = getDirSize(const.cache_path)
> AttributeError: 'module' object has no attribute 'cache_path'
> 
> Traceback (most recent call last):
>   File "/home/tonychyi/Wecase/bin/lib/python3.3/site-packages/WeCase/WeCaseWindow.py", line 480, in showSettings
>     wecase_settings = WeSettingsWindow()
>   File "/home/tonychyi/Wecase/bin/lib/python3.3/site-packages/WeCase/SettingWindow.py", line 22, in **init**
>     self.setupUi(self)
>   File "/home/tonychyi/Wecase/bin/lib/python3.3/site-packages/WeCase/SettingWindow.py", line 29, in setupUi
>     self.showSize()
>   File "/home/tonychyi/Wecase/bin/lib/python3.3/site-packages/WeCase/SettingWindow.py", line 32, in showSize
>     self.cacheSizeLabel.setText(self.getHumanReadableCacheSize())
>   File "/home/tonychyi/Wecase/bin/lib/python3.3/site-packages/WeCase/SettingWindow.py", line 35, in getHumanReadableCacheSize
>     raw_bytes = getDirSize(const.cache_path)
> AttributeError: 'module' object has no attribute 'cache_path'

**Comment by biergaizi** [comment]
重命名模块的时候漏掉了一些文件。以后可能还会有这些问题，请及时汇报。
