### ISSUE TITLE
dev分支的autotools版本不同

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#96]
configure.ac使用automake-1.11.3

**Comment by biergaizi** [comment]
没听懂。

**Comment by cthbleachbit** [comment]
configure里写了是aclocal-1.14，debian/ubuntu的aclocal版本不同，导致make不能正确工作。。。

**Comment by biergaizi** [comment]
那怎么修改……

**Comment by biergaizi** [comment]
P.S：Gentoo 都是无视随代码附带的 aclocal 生成文件的……都会自己运行 aclocal……

**Comment by cthbleachbit** [comment]
我的是autotools-1.14，，，直接改？。

**Comment by biergaizi** [comment]
用 Automake 1.13 怎么样？一定要用 1.11？

**Comment by biergaizi** [comment]
Fixed in 97ccf28.
