### ISSUE TITLE
中键点击微博的文字部分会跳出浏览器

### ISSUE THREAD

**Issue by cthbleachbit** [WeCase/WeCase#97]
如题
![_002](https://f.cloud.github.com/assets/3353318/1795886/6e1a6dba-6a41-11e3-9a3e-e195a521940c.png)
文字部分的意思是上图中箭头的地方

**Comment by biergaizi** [comment]
额，的确是个大 Bug……

**Comment by biergaizi** [comment]
不仅仅是“中键点击被转发微博”，原微博也可以……

根据

```
➜  /tmp  ./WeCase/bin/wecase.py
START /usr/bin/google-chrome-beta "http://"
```

可以初步判断，是点击了没有链接的地方，产生了一个空字符串，默认成了 HTTP 协议，然后浏览器就弹出来了……

**Comment by biergaizi** [comment]
Fixed in dcd8cf4.
